### ISSUE TITLE
Unable to tap `homebrew-core-mojave`: invalid syntax in tap

### ISSUE THREAD

**Issue by whitebear60** [gromgit/homebrew-core-mojave#1]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_CORE_GIT_REMOTE set: using https://github.com/gromgit/homebrew-core-mojave for Homebrew/core Git remote.
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 27232, done.
remote: Counting objects: 100% (734/734), done.
remote: Compressing objects: 100% (707/707), done.
remote: Total 27232 (delta 365), reused 224 (delta 27), pack-reused 26498
Receiving objects: 100% (27232/27232), 12.98 MiB | 5.04 MiB/s, done.
Resolving deltas: 100% (16031/16031), done.
Updating files: 100% (6268/6268), done.
Error: Non-file alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/tiv
Error: Cannot tap homebrew/core: invalid syntax in tap!
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install homebrew-core-mojave tap

### What happened (include all command output)?

Tapping was unsuccessful

### What did you expect to happen?

Successful tapping of homebrew-core-mojave

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
export HOMEBREW_CORE_GIT_REMOTE=https://github.com/gromgit/homebrew-core-mojave
rm -fr $(brew --repo homebrew/core)
brew tap homebrew/core https://github.com/gromgit/homebrew-core-mojave
```

**Comment by gromgit** [comment]
Sorry, that alias was checked in before the corresponding formula (`terminalimageviewer`), which is still WIP. I've removed it for now.
