### ISSUE TITLE
high sierra 10.13 support?

### ISSUE THREAD

**Issue by ipatch** [gromgit/homebrew-core-mojave#3]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
you know of any taps like this one that offering bottles for high sierra at all?

and thank you for providing this tap. 🙏
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

na

### What happened (include all command output)?

na

### What did you expect to happen?

na

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
na
```

**Comment by gromgit** [comment]
Sorry, no, and given the ridiculous number of issues I'm still encountering with Mojave builds, I suspect it's no coincidence. It seems that once Apple (and Homebrew) drops support for a specific OS version, the rest of the world follows suit rather quickly.

**Comment by ipatch** [comment]
![mike jordan cry](https://user-images.githubusercontent.com/613805/156593337-57e21973-74a9-4b06-93b9-dba664c9c473.jpg)
