### ISSUE TITLE
invalid formula / casks style_exceptions

### ISSUE THREAD

**Issue by ipatch** [gromgit/homebrew-core-mojave#4]
i'm attempting to use this repo for the mojave bits of the homebrew-freecad ci/cd, and have been running into the below issuse when attempting build some bottles using brew test-bot

```shell
brew audit freecad/freecad/shiboken2@5.15.3 --online --new-formula
homebrew/core:
  * style_exceptions/binary_bootstrap_formula_urls_allowlist.json references
    formulae or casks that are not found in the homebrew/core tap.
    Invalid formulae or casks: go@1.9, go@1.10, go@1.11, go@1.12
Error: 1 problem in 1 tap detected
```

seems liked it'd make sense to update that list to remove such offendeding formula because they are not in this tap.

what are your thoughts on this?

**Comment by gromgit** [comment]
Sorry about that, there were some changes to `style_exceptions/binary_bootstrap_formula_urls_allowlist.json` and other miscellaneous files that hadn't been pushed. Please `brew update` and see if it's still happening for you.

**Comment by ipatch** [comment]
nice, i see you removed those offeneding go packages from style exception list. funny you made these changes this evening as i went down a **bsd** flavored sed search rabbit hole to come up with an expression that could remove those lines from the file.

https://github.com/FreeCAD/homebrew-freecad/blob/2573630c972d3943069992686cf0e5e0d34bd3ef/.github/workflows/tests.yml#L96

---

either way thanks for updating the repo, and i got to brush up on my ~~sed skills~~, and read about how people state that this is a task for `awk` and not ~~sed~~ or how bsd sed doesn't have all the bells and whistles of gnu sed 😭
