### ISSUE TITLE
qt@5 upstream has been updated

### ISSUE THREAD

**Issue by ipatch** [gromgit/homebrew-core-mojave#6]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
you mind updating qt@5 to build new bottles for qt@5 ?

it's been updated from 5.15.3 to 5.15.5

---

is there a way to can trigger a rebuild of the bottle for this repo or is that something you only have access to?
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

update qt@5 to latest version

### What happened (include all command output)?

formula still references old bottle and tarball

### What did you expect to happen?

new version

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
na
```

**Comment by gromgit** [comment]
Done, apologies for the delay.
