### ISSUE TITLE
qt@5 is outdated

### ISSUE THREAD

**Issue by ipatch** [gromgit/homebrew-core-mojave#7]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
na
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install the latest version of qt@5 without having to build from source (if possible) would prefer to install from bottle.  that said, i believe this version of qt is missing components related to the webengine.

### What happened (include all command output)?

na

### What did you expect to happen?

have a complete working install of qt@5

link to the upstream version of qt@5

https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt%405.rb

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install qt@5
```

**Comment by gromgit** [comment]
I've updated the `qt@5` bottle, but as for missing components, I'm tracking Homebrew core, so anything they don't include will also not be included here.
